function rhs=rhs_u(u,v,h,nx,ny,dx,dy,g,f)
	x=2:nx+1; y=2:ny+1;
	rhs = -u(y,x).*(u(y,x+1)-u(y,x-1))/(2*dx) ...
	  	  -v(y,x).*(u(y+1,x)-u(y-1,x))/(2*dy) ...
		    -g*(h(y,x+1)-h(y,x-1))/(2*dx) ...
		    +f*v(y,x);
end
